const CONST = {
  BASE_URL_API: process.env.REACT_APP_BASE_URL,
  REACT_APP_KEY_ID: process.env.REACT_APP_KEY_ID,

  FIREBASE_KEY: process.env.REACT_APP_FIREBASE_KEY,
  FIREBASE_DOMAIN: process.env.REACT_APP_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.REACT_APP_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.REACT_APP_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING: process.env.REACT_APP_FIREBASE_MESSAGING,
  FIREBASE_APP_ID: process.env.REACT_APP_FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID: process.env.REACT_APP_FIREBASE_MEASUREMENT_ID,
};

export default CONST;
